### ISSUE TITLE
Packaging R for WebAssembly

### ISSUE THREAD

**Issue by IsabelParedes** [emscripten-forge/recipes#1050]
## r-base

- [x] Figuring out configuration and cross-compilation
    - https://github.com/IsabelParedes/emscripten-forge-recipes/tree/r-base-flang
- lang: R, C, Fortran
- [x] Package `r-base` for emscripten-forge
    - #1287  
    - **Requires:**
        - [x] Patched `flang-new` available on conda-forge/label/llvm_dev (for linux)
            - https://github.com/conda-forge/flang-feedstock/pull/69
        - [x] A recipe to build the Fortran Runtime on emscripten-forge (for wasm)
            - #1285 
        - [x] `libblas`
            - lang: Fortran
            - Builds with patched `flang-new`
            - #1284 
        - [x] `liblapack`
            - lang: Fortran
            - Builds with patched `flang-new`
            - #1284 

 <details><summary>Other dependencies</summary>
 
- [x] `xz` #1055
- [x] ~~`libcurl`~~ (NOT NEEDED / wouldn't work!)
- [x] `cairo` #1109
    - deps: `glib`, `pixman`
- [x] `pixman` #1058 
- [x] `glib` #1051
- [x] `pango` fancy text rendering (optional) #1398
    - deps: `cairo`, `harfbuzz`
- [x] `harfbuzz` #1067
    - [x] deps: `graphite2` #1057
- [x] `icu` #1043
- [x] `libiconv`
- [x] `zlib`
- [x] `libtiff`
- [x] `libpng`
- [x] `bzip2`
- [x] `pcre2` #1041
- [x] <s>`libjpeg-turbo`</s> `jpeg` #1052
- [x] <s>`tk`</s>
- [x] <s>`bwidget`</s>
    - deps: `tk`
- [x] <s>`tktable`</s>
    - deps: `tk`
- [x] <s>`readline`</s> 
    - [x] dep: `ncurses` #882
            
</details>

## R packages

All of the following packages depend on `r-base` and are dependencies for `xeus-r`.

- [x] `r-rlang` #1303 
- [x] `r-evaluate` **noarch**
- [x] `r-jsonlite` #1307 
- [x] `r-glue` #1306 
- [x] `r-cli` #1364 Only <v3.0.1 **noarch**
- [x] `r-repr` **noarch**
    - dependencies:
        - `r-base`
        - [x] `r-base64enc` #1314 
        - [x] `r-htmltools` #1345 
            - lang: R, C
            - dependencies:
                - `r-base`
                - `r-base64enc`
                - `r-rlang`
                - [x] `r-digest` #1308 
                - [x] `r-ellipsis` #1343 
                    - lang: R, C
                    - dep: `r-rlang`
                - [x] `r-fastmap` #1309 
        - [x] `r-pillar` **noarch**
            - dependencies:
                - `r-base`
                - `r-cli`
                - `r-ellipsis`
                - `r-rlang`
                - [x] (optional) `r-crayon` **noarch**
                    - *Superseded by* `r-cli`
                    - lang: R
                    - deps: `r-base`
                - [x] `r-fansi` #1311 
                - [x] `r-lifecycle` **noarch**
                - [x] `r-vctrs` #1342 
                    - lang: R, C
                    - dependencies:
                        - `r-base`
                        - `r-rlang`
                        - `r-cli`
                        - `r-glue`
                        - `r-lifecycle`
                - [x] `r-utf8` #1313 
- [x] `r-IRdisplay` **noarch**
    - dependencies:
        - `r-base`
        - `r-repr`
- [x] `r-ggplot2` **noarch**
    - dependencies:
        - `r-base`
        - `r-rlang`
        - `r-cli`
        - `r-glue`
        - `r-lifecycle`
        - `r-vctrs`
        - [x] `r-mass` #1315 
        - [x] `r-gtable` **noarch**
        - [x] `r-isoband` #1316 
        - [x] `r-mgcv` #1340 
            - [x] `nlme` #1338 
            - [x] `matrix` #1339 
            - [x] `lattice` #1317 
        - [x] `r-scales` **noarch**
            - [x] `r-farver` #1323 
        - [x] `r-tibble` #1347 
        - [x] `r-magrittr` #1324 
        - [x] `r-withr` **noarch**

## r-coursekata

- [x] `r-coursekata` (**noarch**)
    - [x] `r-purrr` >=0.3.4 #1348 
    - [x] `r-metrics` (**noarch**)
    - [x] `r-dslabs` (**noarch**)
    - [x] `r-ggformula` (**noarch**)
    - [x] `r-lsr` (**noarch**)
    - [x] `r-mosaic` (**noarch**)
    - [x] `r-pak` (**noarch**)
    - [x] `r-palmerpenguins` (**noarch**)
    - [x] `r-supernova` (**noarch**)
    - [x] `r-viridislite` (**noarch**)

**Comment by SylvainCorlay** [comment]
https://github.com/conda-forge/r-coursekata-feedstock

**Comment by IsabelParedes** [comment]
As a side note, I tried building `r-base` with `clapack` and `openblas` which are already available on `emscripten-forge`. However, `r-base` still has an internal `appl` lib which requires having a Fortran to WebAssembly toolchain.

**Comment by adamblake** [comment]
@IsabelParedes @SylvainCorlay I got a new requirement for this project which is the neuralnet package. It looks like it is noarch, but has a dependency on MASS (already packaged on this issue) and Deriv (not yet packaged). I checked and Deriv only depends on r-base, so I think we are good, right?

- r-neuralnet meta: https://github.com/conda-forge/r-neuralnet-feedstock/blob/main/recipe/meta.yaml
- r-deriv meta: https://github.com/conda-forge/r-deriv-feedstock/blob/main/recipe/meta.yaml

**Comment by IsabelParedes** [comment]
> @IsabelParedes @SylvainCorlay I got a new requirement for this project which is the neuralnet package. It looks like it is noarch, but has a dependency on MASS (already packaged on this issue) and Deriv (not yet packaged). I checked and Deriv only depends on r-base, so I think we are good, right?
> 
> - r-neuralnet meta: https://github.com/conda-forge/r-neuralnet-feedstock/blob/main/recipe/meta.yaml
> 
> - r-deriv meta: https://github.com/conda-forge/r-deriv-feedstock/blob/main/recipe/meta.yaml

Hi @adamblake! Correct, these two packages do not need compilation so they're good to go.
